name: portfolio_plus
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.10+1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  fpdart: ^1.1.0
  firebase_core: ^2.27.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dev: ^1.0.0
  internet_connection_checker: ^1.0.0+1
  firebase_auth: ^4.17.8
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.15.8
  get_it: ^7.6.7
  image_picker: ^1.0.8
  firebase_storage: ^11.6.9
  bloc_concurrency: ^0.2.5
  drop_down_list: ^0.0.7
  flex_color_scheme: ^7.3.1
  cached_network_image: ^3.3.1
  flutter_spinkit: ^5.2.1
  page_transition: ^2.1.0
  uuid: ^4.4.2
  intl: ^0.19.0
  firebase_messaging: ^14.7.19
  toastification: ^2.1.0
  http: ^1.2.0
  googleapis_auth: ^1.6.0
  dio: ^5.6.0
  path_provider: ^2.1.4
  extended_image: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.9
  hive_generator: ^2.0.1

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true


  assets:
    - assets/images/svg/

  fonts:
    - family: Drillos
      fonts:
        - asset: assets/fonts/Drillos.ttf
    - family: ParadiseLove
      fonts:
        - asset: assets/fonts/ParadiseLove.ttf
    - family: Brilliant
      fonts:
        - asset: assets/fonts/Brilliant.ttf
